name: Deploy to VPS

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.x'
    - name: Install dependencies
      run: go get .
    - name: Build
      run: go build -v ./server.go
    - name: Zip exe and project files
      run: zip -r deployment-package.zip ./*
    - name: Upload all files
      uses: actions/upload-artifact@v4
      with:
        name: deployment-package
        path: deployment-package.zip
    
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download deployment package
      uses: actions/download-artifact@v4
      with:
        name: deployment-package

    - name: Extract deployment package
      run: unzip deployment-package.zip -d extracted_files

    - name: Copy files to VPS
      env:
        SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -H 5.78.103.231 >> ~/.ssh/known_hosts
        rsync -avz --delete extracted_files/ jimmy@5.78.103.231:/var/www/jimmys-place/

    - name: Restart Go server
      env: 
        SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
      run: |
        ssh -i ~/.ssh/id_ed25519 jimmy@5.78.103.231 "sudo systemctl restart jimmysplace"
